# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: E2E

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-e2e:
    if: (github.repository == 'Azure-Samples/microsoft-identity-express') && (github.actor != 'dependabot[bot]') && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push'))
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 14, 16, 18 ]

    name: Node v${{ matrix.node }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Clean Install
      env:
        RUNNING_NODE_CI: 1
      run: npm ci

    - name: Install Sample
      working-directory: demo
      run: |
        npm run install:local
        npm install

    - name: E2E Tests
      working-directory: demo
      timeout-minutes: 10
      env:
        AAD_CLIENT_SECRET: ${{ secrets.AAD_CLIENT_SECRET }}
        AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
        AAD_CLIENT_ID: ${{ secrets.AAD_CLIENT_ID }}
        AAD_TEST_USER_USERNAME: ${{ secrets.AAD_TEST_USER_USERNAME }}
        AAD_TEST_USER_PASSWORD: ${{ secrets.AAD_TEST_USER_PASSWORD }}
        ADD_SECURITY_GROUP_ID: ${{ secrets.ADD_SECURITY_GROUP_ID }}
        ADD_LEAST_PRIVILEGE_TEST_USER_USERNAME: ${{ secrets.ADD_LEAST_PRIVILEGE_TEST_USER_USERNAME }}
        ADD_LEAST_PRIVILEGE_TEST_USER_PASSWORD: ${{ secrets.ADD_LEAST_PRIVILEGE_TEST_USER_PASSWORD }}
        B2C_CLIENT_ID: ${{ secrets.B2C_CLIENT_ID }}
        B2C_TENANT_ID: ${{ secrets.B2C_TENANT_ID }}
        B2C_CLIENT_SECRET: ${{ secrets.B2C_CLIENT_SECRET }}
        B2C_TEST_USER_USERNAME: ${{ secrets.B2C_TEST_USER_USERNAME }}
        B2C_TEST_USER_PASSWORD: ${{ secrets.B2C_TEST_USER_PASSWORD }}
        B2C_AUTHORITY: ${{ secrets.B2C_AUTHORITY }}
      run: npm test

    - name: Upload E2E Test Screenshots
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: e2e-test-screenshots
        path: demo/test/screenshots
